travis:
  secure:
    BINSTAR_TOKEN: PX8lRGxnrF4TfEYSMNWP5brdLt6hx8pNdwmoSIt3UvdSxSDeMNo0RimdKndBQF1h41GKPmr9FnIv7svJ2FMcTcQVCDNXa3iqKNgK0uPohl3VHh08iUp7wZ8eVo/Ayic9AIvwrn499HpIluzZSCcNDT6z+/InGkalFBYc53+0l3wVNICmFYj7IWEILC/bE680ovtlCbi4A2o6Krlz6KDDvwznOUlNt61Qz0f1HAb3MJZlViGHx/wiwUdSX7MqQP9ow/qdioEItXXurOnj1gJJkoDIYVCZWVO//+c6+gJsFIZrGKEqvQ4GTzyCqThwb5+FflSXKFW6cxzIvzRltJeQVgtLig61YOMHWDXwgvySNvgQMUb1ti35Qg2WrKuaLlvbh5tY7dxHySeah44HrwiKP38WLtffLt3ODV0bsxxvdgO6+IMndST4A53aJlpWwCATwrDHUFWlWe82DtC6tsfTDSNWSk9xdhEBuCO5KOgD2h70xCVA80ZOao5iS6XYIsdJy+WuetUbo2JwpR4DFCqBzoZisuRrWoJNv2bADr05/9dXkePvID1398hHMz9iuM0KAUAsKVRNikqdiC+86GQ+PKnhlaiAkdapRZMV0/5hMK5B1RZXY/6t1ErR2U6PQ0Zw/LM5/8o1QB3R1JUscpX/J6jJcPA0ZKSArr/CScnmv4w=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
